services:
    postgres:
        image: postgres:16.0
        container_name: postgres
        environment:
         POSTGRES_PASSWORD: admin
         POSTGRES_USER: admin
         POSTGRES_DB: taxi_db
        ports:
           - "5432:5432"
        healthcheck:
           test: ["CMD", "pg_isready", "-U", "admin", "-d", "taxi_db"]
           interval: 5s
           timeout: 5s
           retries: 5
        volumes:
          - db_data:/var/lib/postgresql/data
          - ./1_container_extraction/init.sql:/docker-entrypoint-initdb.d/init.sql

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: "GvV9o@example.com"
            PGADMIN_DEFAULT_PASSWORD: "admin"
        ports:
            - "5050:80"
        depends_on:
            - postgres
        restart: always
        volumes:
            - pgadmin:/var/lib/pgadmin


    container_extraction:
        build: ./1_container_extraction
        container_name: 1_container_extraction
        environment:
            DB_NAME: taxi_db
            DB_USER: admin
            DB_PASSWORD: admin
        volumes:    
            - ./data:/data
        depends_on:
            - postgres
    
    container_dbt:
        build: ./2_container_dbt
        container_name: 2_container_dbt
        environment:
            DB_USER: admin
            DB_PASSWORD: admin
        volumes:
            - ./2_container_dbt:/dbt
        depends_on:
            postgres:
                condition: service_healthy
    
    clickhouse:
        image: clickhouse/clickhouse-server:24.3
        container_name: clickhouse
        environment:
            CLICKHOUSE_USER: admin
            CLICKHOUSE_PASSWORD: admin
            CLICKHOUSE_DB: taxi_marts
        ports:
            - "8123:8123"
            - "9000:9000"
        volumes:
            - ch_data:/var/lib/clickhouse
        healthcheck:
            test: ["CMD", "clickhouse-client", "--user", "admin", "--password", "admin", "--query", "SELECT 1"]
            interval: 5s
            timeout: 5s
            retries: 5

    container_python2clickhouse:
        build: ./3_container_python2clickhouse
        container_name: 3_container_python2clickhouse
        environment:
            DB_USER: admin
            DB_PASSWORD: admin
        depends_on:
            postgres:
                condition: service_healthy
            clickhouse:
                condition: service_healthy
    
    container_python2tableau:
        build: ./4_container_python2tableau
        container_name: 4_container_python2tableau
        depends_on:
            clickhouse:
                condition: service_healthy
        volumes:
            - ./data/tableau:/data/tableau

volumes:
    db_data:
    pgadmin:
    ch_data:

